name: 'Focalboard ARM64 Build'

env:
  DOCKERHUB_REPO: dexter2389/focalboard

# Trigger on release
on:
  workflow_dispatch:
    types: [focalboard]
    branches: [main]
    client_payload:
      release_version:
        description: "release focalboard version"
        required: true
      release_tag:
        description: "release focalboard tag"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Docker image labels
        uses: crazy-max/ghaction-docker-meta@v2.5.0
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          label-custom: |
            maintainer=dexter2389
            org.opencontainers.image.title=focalboard
            org.opencontainers.image.description=Focalboard is an open source, self-hosted alternative to Trello, Notion, and Asana.
            org.opencontainers.image.url=https://www.focalboard.com
            org.opencontainers.image.licenses=Mattermost Licensing
            org.opencontainers.image.version=${{github.event.client_payload.release_version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sync README To DockerHub
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
          readme: ./Focalboard/README.md
          slug: ${{ env.DOCKERHUB_REPO }}

      - name: Build and Push - rc
        uses: docker/build-push-action@v2
        if: ${{contains(github.event.client_payload.release_version, 'rc')}}
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Focalboard/Dockerfile
          platforms: linux/arm64
          push: true
          build-args: FOCALBOARD_REF=${{github.event.client_payload.release_tag}}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{github.event.client_payload.release_version}}
          labels: ${{ steps.docker_meta.outputs.labels }}
          
      - name: Build and Push - main release
        uses: docker/build-push-action@v2
        if: ${{!contains(github.event.client_payload.release_version, 'rc')}}
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Focalboard/Dockerfile
          platforms: linux/arm64
          push: true
          build-args: FOCALBOARD_REF=${{github.event.client_payload.release_tag}}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{github.event.client_payload.release_version}}
            ${{ env.DOCKERHUB_REPO }}:latest
          labels: ${{ steps.docker_meta.outputs.labels }}
